'use client';
import { FormEvent, useState } from 'react';
const API = process.env.NEXT_PUBLIC_API_BASE_URL || 'http://localhost:4000';
type Result = { shipment: {tracking_id:string;status:string;progress_percent:number;origin_country:string;destination_country:string;current_location:string|null;estimated_delivery:string|null;shipment_date:string;package_type:string;weight_kg:string}; events: {status:string;progress_percent:number;location:string|null;note:string|null;occurred_at:string}[] };
export default function Home(){
 const [id,setId]=useState(''); const [data,setData]=useState<Result|null>(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setError('');setData(null);setLoading(true);try{const r=await fetch(`${API}/api/track/${encodeURIComponent(id)}`);const j=await r.json();if(!r.ok)throw new Error(j.error||'Tracking lookup failed');setData(j);}catch(err){setError(err instanceof Error?err.message:'Unable to connect to tracking service');}finally{setLoading(false)}}
 return <><nav className="nav"><strong>WORLD COURIER DELIVERY</strong><span>Shipment tracking</span></nav><section className="hero"><div className="wrap"><p>GLOBAL SHIPPING · RELIABLE DELIVERY</p><h1>Track your shipment</h1><p>Enter your tracking ID to view the latest shipment status.</p></div></section><main className="panel"><h2>Track a package</h2><form className="form" onSubmit={submit}><input aria-label="Tracking ID" value={id} onChange={e=>setId(e.target.value)} placeholder="Enter tracking ID" required/><button disabled={loading}>{loading?'Checking…':'Track shipment'}</button></form>{error&&<p role="alert">{error}</p>}{data&&<section className="status"><h3>{data.shipment.status}</h3><p><b>{data.shipment.tracking_id}</b> · {data.shipment.progress_percent}% complete</p><progress max="100" value={data.shipment.progress_percent} style={{width:'100%'}}/><p>{data.shipment.origin_country} → {data.shipment.destination_country}</p><p>Current location: {data.shipment.current_location||'Update pending'}</p><p>Estimated delivery: {data.shipment.estimated_delivery||'Not available'}</p><h4>Tracking history</h4>{data.events.length?data.events.map((event,i)=><p key={i}>• {new Date(event.occurred_at).toLocaleString()} — {event.status}{event.location?` · ${event.location}`:''}{event.note?` — ${event.note}`:''}</p>):<p className="muted">No tracking events yet.</p>}</section>}</main><footer className="footer">World Courier Delivery · Contact support for shipment assistance.</footer></>;
}
